OFFICIALLY_ASSIGNED, USER_ASSIGNED = ["officially-assigned", "user-assigned"]
VALID_COUNTRIES_STATUSES = [OFFICIALLY_ASSIGNED, USER_ASSIGNED]

AFRICA, AMERICAS, ANTARCTIC, ASIA, EUROPE, OCEANIA = ["Africa", "Americas", "Antarctic", "Asia", "Europe", "Oceania"]
VALID_REGIONS = [AFRICA, AMERICAS, ANTARCTIC, ASIA, EUROPE, OCEANIA]

[
    AUSTRALIA_AND_NEW_ZEALAND,
    CARIBBEAN,
    CENTRAL_AMERICA,
    CENTRAL_ASIA,
    CENTRAL_EUROPE,
    EASTERN_AFRICA,
    EASTERN_ASIA,
    EASTERN_EUROPE,
    MELANESIA,
    MICRONESIA,
    MIDDLE_AFRICA,
    NORTH_AMERICA,
    NORTHERN_AFRICA,
    NORTHERN_EUROPE,
    POLYNESIA,
    SOUTH_AMERICA,
    SOUTH_EASTERN_ASIA,
    SOUTHEAST_EUROPE,
    SOUTHERN_AFRICA,
    SOUTHERN_ASIA,
    SOUTHERN_EUROPE,
    WESTERN_AFRICA,
    WESTERN_ASIA,
    WESTERN_EUROPE,
] = [
    "Australia and New Zealand",
    "Caribbean",
    "Central America",
    "Central Asia",
    "Central Europe",
    "Eastern Africa",
    "Eastern Asia",
    "Eastern Europe",
    "Melanesia",
    "Micronesia",
    "Middle Africa",
    "North America",
    "Northern Africa",
    "Northern Europe",
    "Polynesia",
    "South America",
    "South-Eastern Asia",
    "Southeast Europe",
    "Southern Africa",
    "Southern Asia",
    "Southern Europe",
    "Western Africa",
    "Western Asia",
    "Western Europe",
]
VALID_SUBREGIONS = [
    AUSTRALIA_AND_NEW_ZEALAND,
    CARIBBEAN,
    CENTRAL_AMERICA,
    CENTRAL_ASIA,
    CENTRAL_EUROPE,
    EASTERN_AFRICA,
    EASTERN_ASIA,
    EASTERN_EUROPE,
    MELANESIA,
    MICRONESIA,
    MIDDLE_AFRICA,
    NORTH_AMERICA,
    NORTHERN_AFRICA,
    NORTHERN_EUROPE,
    POLYNESIA,
    SOUTH_AMERICA,
    SOUTH_EASTERN_ASIA,
    SOUTHEAST_EUROPE,
    SOUTHERN_AFRICA,
    SOUTHERN_ASIA,
    SOUTHERN_EUROPE,
    WESTERN_AFRICA,
    WESTERN_ASIA,
    WESTERN_EUROPE,
    None,
]

ANTARCTICA = "Antarctica"
VALID_CONTINENTS = [AFRICA, ANTARCTICA, ASIA, EUROPE, NORTH_AMERICA, OCEANIA, SOUTH_AMERICA]

[MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY] = [
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
]
VALID_START_OF_THE_WEEK = [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY]
